version: '3'
services:
  api:
    container_name: api
    build: .
    volumes:
      - ./:/usr/src/application:ro
    command: uvicorn index:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000